# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: monstecho
subtitle: 天马行空的幻想
description: 我爱你，即使连死亡也无法阻挡
keywords: 二次元,编程,游戏,博客,monstecho
author: monstecho
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://www.monstecho.top
permalink: posts/:abbrlink/ 
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solitude

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:mostecho/mostecho.github.io.git
  branch: main

# https://github.com/hexojs/hexo-generator-feed
#Feed Atom
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 60
  content:

# 文章链接转数字或字母：https://github.com/rozbo/hexo-abbrlink
abbrlink:
    alg: crc16   #算法： crc16(default) and crc32
    rep: hex     #进制： dec(default) and hex: dec #输出进制：十进制和十六进制，默认为10进制。丨dec为十进制，hex为十六进制

# hexo-safego安全跳转插件
# see https://blog.liushen.fun/posts/1dfd1f41/
hexo_safego:
  general:                        # 基本功能设置
    enable: true                # 启用插件
    enable_base64_encode: true  # 使用 Base64 编码
    enable_target_blank: true   # 从新窗口打开跳转页面
  security:                     # 安全设置
    url_param_name: 'u'         # URL 参数名
    html_file_name: 'go.html'   # 重定向页面的文件名
    ignore_attrs:               # 忽略处理的 HTML 结构
      - 'data-fancybox'
  scope:                        # 容器与页面设置
    apply_containers:           # 应用的容器选择器
      - '#post'
      - '#links'
    apply_pages:                # 应用的页面路径
      - "/posts/"
      - "/tags/"
      - "/history/"
      - "/essays/"
      - "/links/"
      - "/message/"
      - "/tools/"
    exclude_pages:
      # - "/about/" 
  whitelist:                    # 域名白名单
    domain_whitelist:           # 允许的白名单域名，通过字符串匹配实现
      - "mostecho.github.io"
      - "www.monstecho.top"
  appearance:                   # 页面外观设置
    avatar: https://bu.dusays.com/2025/04/13/67faa29addd90.png  # 跳转页面头像路径
    title: "monstecho"            # 跳转页面标题
    subtitle: "安全中心提示你不要乱点，它与本站不存在法律裙带关系ヽ（≧□≦）ノ"         # 跳转页面副标题
    darkmode: false             # 是否启用深色模式
    countdowntime: 5           # 跳转页面倒计时秒数，如果设置为负数则为不自动跳转
  debug:                        # 调试设置
    enable: false               # 启用调试模式

    sitemap:
      path: sitemap.xml
      priority: 0.5
      changefreq: daily
      lastmod: true