name: Deploy blog to GitHub
on:  # 在有推送时触发，同时保留手动触发的功能
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "latest"

    - name: Install Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g

    - name: Install deps
      run: |
        npm install --save

    - name: Generate static files
      run: |
        hexo clean
        node ./link.js
        hexo generate

    - name: Deploy
      run: |
        git clone https://github.com/[你的 GitHub 用户名]/[你的被部署仓库] # 克隆被部署仓库
        cd BLOG || exit 1
        # 以下两行，是为了解决只复制文件，可能会导致我们想要删除一些内容的时候，被部署仓库里不会同步更新的问题
        rm -rf *
        cd ..

        cp -rf ./public/* BLOG/
        cd BLOG
        # 配置 git
        git config --global user.name '[你的 GitHub 用户名]'
        git config --global user.email '[你的邮箱]'
        git add --all
        git commit -m "Auto deployment: ${{ github.event.head_commit.message }}

        TIME: $(TZ='Asia/Shanghai' date +"UTC+8 %Y-%m-%d %A %H:%M:%S")"
        git push --set-upstream "https://[你的 GitHub 用户名]:[你的GitHub Token]@github.com/[你的用户名]/[你的被部署仓库]" main --force